In [22]:
import numpy as np
from scipy.signal import convolve2d

input = np.random.randint(1, 10, size=(3, 3))
kernel = np.random.randint(0, 3, size=(2, 2))

print(input)
print(kernel)

[[4 6 8]
 [8 2 9]
 [3 8 8]]
[[0 2]
 [1 1]]


In [24]:
in_height, in_width = np.shape(input)
ker_height, ker_width = np.shape(kernel)
out_height = in_height - ker_height + 1
out_width = in_width - ker_width + 1
print(out_height, out_width)

2 2


In [26]:
output = np.zeros((out_height, out_width))

for i in range(0, out_height):
    for j in range(0, out_width):
        for ii in range(0, ker_height):
            for jj in range(0, ker_width):
                output[i, j] += input[i+ii, j+jj] * kernel[ii, jj]
print(output)

[[22. 27.]
 [15. 34.]]


In [28]:
output2 = convolve2d(input, np.fliplr(np.flipud(kernel)), mode='valid')
print(output2)

[[22 27]
 [15 34]]
