# Softmax in code

In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)
a

array([ 0.29585007, -1.04363255, -0.9339663 ,  1.52139824, -1.24383858])

In [4]:
expa = np.exp(a)
expa

array([1.3442686 , 0.35217307, 0.39299189, 4.57862273, 0.28827552])

In [5]:
answer = expa/np.sum(expa)
answer

array([0.19324389, 0.05062626, 0.05649413, 0.65819499, 0.04144074])

In [6]:
total_prob = np.sum(answer)
total_prob

np.float64(1.0)

In [8]:
A = np.random.randn(100, 5)  # 100 samples, 5 classes
A

array([[-0.3420221 , -0.4603584 , -1.2118828 , -0.02890886, -0.51700993],
       [-1.28488396,  0.85167394, -0.29292845,  0.23480464, -0.80558924],
       [ 1.19085892, -1.24352793,  0.7011778 ,  1.47364275,  0.77910991],
       [ 0.87800808, -0.10781557, -1.24453863,  0.70650251,  0.3369054 ],
       [-0.12227723,  1.10118869, -1.42300591,  0.13120969,  1.3218239 ],
       [ 0.85924292,  2.05254402,  0.40637086, -0.88103014, -0.21364882],
       [ 0.14316769, -1.78384699,  0.29329903, -1.09443216,  0.98010368],
       [ 1.65079754, -1.76163486, -0.98809036,  0.38995898, -0.27368818],
       [ 1.65331515,  0.64046543, -1.09263692, -0.38035598, -1.82407927],
       [-0.81210074, -0.45646509,  0.42055638,  2.22466443, -0.20861659],
       [-0.85869325,  0.12180195,  0.15130267,  1.8065    ,  0.85783008],
       [ 0.35692553, -0.22451647, -1.0872888 , -1.29454089, -1.83320179],
       [-0.57231806,  0.0985425 , -0.31103694, -0.39858658, -0.8681015 ],
       [-0.28972658,  0.23406978, -0.8

In [9]:
expA = np.exp(A)
expA

array([[ 0.71033251,  0.63105744,  0.29763636,  0.971505  ,  0.59630086],
       [ 0.27668269,  2.34356655,  0.74607552,  1.26466168,  0.44682456],
       [ 3.28990575,  0.28836509,  2.01612591,  4.36510722,  2.17953143],
       [ 2.40610216,  0.89779316,  0.28807379,  2.02688982,  1.40060656],
       [ 0.88490301,  3.00773917,  0.24098854,  1.14020684,  3.75025524],
       [ 2.36137226,  7.78768799,  1.50135924,  0.41435585,  0.80763196],
       [ 1.15392329,  0.16799064,  1.34084369,  0.33472963,  2.6647325 ],
       [ 5.21113424,  0.17176382,  0.37228695,  1.47692021,  0.7605692 ],
       [ 5.22427038,  1.89736376,  0.33533109,  0.68361801,  0.16136615],
       [ 0.44392452,  0.63351913,  1.52280858,  9.25037812,  0.81170639],
       [ 0.42371541,  1.12953037,  1.16334872,  6.08909822,  2.35803838],
       [ 1.42892945,  0.79890242,  0.33712928,  0.27402364,  0.15990078],
       [ 0.56421604,  1.1035613 ,  0.73268681,  0.67126816,  0.41974768],
       [ 0.74846819,  1.26373267,  0.4

In [22]:
answer = expA / expA.sum(axis=1, keepdims=True)
answer

array([[0.22150598, 0.1967853 , 0.0928132 , 0.3029485 , 0.18594701],
       [0.05448858, 0.46153087, 0.14692857, 0.24905647, 0.08799551],
       [0.27101871, 0.02375519, 0.16608617, 0.35959259, 0.17954733],
       [0.34277569, 0.1279005 , 0.04103928, 0.28875273, 0.1995318 ],
       [0.09806005, 0.333301  , 0.02670502, 0.12635141, 0.41558252],
       [0.1834445 , 0.6049908 , 0.11663391, 0.03218946, 0.06274133],
       [0.20379345, 0.02966869, 0.23680531, 0.05911633, 0.47061623],
       [0.6519888 , 0.02149016, 0.04657852, 0.18478423, 0.09515829],
       [0.62928237, 0.22854437, 0.04039185, 0.08234428, 0.01943714],
       [0.03505866, 0.05003177, 0.12026284, 0.73054274, 0.064104  ],
       [0.03795464, 0.10117857, 0.10420788, 0.54543577, 0.21122314],
       [0.47648682, 0.26639977, 0.11241819, 0.09137516, 0.05332007],
       [0.16159796, 0.31607264, 0.20984992, 0.19225892, 0.12022056],
       [0.21175309, 0.35752929, 0.12534531, 0.18314313, 0.12222919],
       [0.03421389, 0.28072965, 0.

In [23]:
answer.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
prediction_labels = np.argmax(answer, axis=1)
prediction_labels

array([3, 1, 3, 0, 4, 1, 4, 0, 0, 3, 3, 0, 1, 1, 1, 1, 1, 4, 4, 2, 3, 1,
       0, 4, 2, 2, 0, 4, 0, 0, 0, 1, 2, 4, 4, 0, 0, 0, 0, 0, 2, 3, 0, 1,
       3, 4, 3, 1, 3, 0, 4, 0, 1, 4, 3, 1, 4, 3, 0, 2, 2, 3, 2, 2, 3, 0,
       2, 0, 4, 0, 3, 3, 0, 2, 3, 1, 4, 3, 2, 2, 1, 1, 0, 2, 1, 3, 1, 0,
       1, 2, 2, 0, 0, 4, 2, 2, 1, 1, 1, 0])